
function catchDo(task, onError){
	const fn = () => task().catch(onCatch);
	const onCatch = onError(fn);
	return fn();
}

module.exports = catchDo;
